### ISSUE TITLE
Env specific config values and code promotion

### ISSUE THREAD

**Issue by asunar** [symphoniacloud/programming-aws-lambda-book#10]
Do you have any suggestions on how to create env specific template.yaml files and promote code to different envs like dev/staging and prod?
 For ex. we ended up creating Parameters in the template.yaml file like this. (Lambda function needs to connect to an RDS db inside a VPC)

```
Parameters:
  SqlSecurityGroupId:
    Type: String
  LambdaSubnet:
    Type: String
```

Later in the template.yaml file we referenced these parameters in the function resource config section, like this.

```
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/index.handleSlackEvent
      Runtime: nodejs12.x
      MemorySize: 128
      Timeout: 100
      Description: test
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref DevOpsSlackbotApiGateway
            Path: '/devops/slack'
            Method: post
      VpcConfig:
        SecurityGroupIds:
        - !Ref SqlSecurityGroupId
        SubnetIds:
        - !Ref LambdaSubnet
```

Once they are in place, we can call the corresponding deploy method from make passing in the correct (DEV/STAGE/PROD) parameters to sam

```
        @sam deploy \
                --parameter-overrides $(DEV_OVERRIDES) \
                --profile $(DEV_AWS_PROFILE_NAME) \
                --tags $(DEV_TAGS) \
                --s3-bucket $(DEV_S3_BUCKET) \
                $(DEPLOY_ARGS)

```
Given that this is a fairly common task, I was wondering if there are ways to simplify the process.

**Comment by mikebroberts** [comment]
My preference is to use the same template for all environments - otherwise it's super easy for production and non-production environments to get out of sync.

CloudFormation doesn't make this pretty, but I do the following:
- I pass in a CloudFormation parameter for environment (e.g. `Env`)
- I use CloudFormation Mappings to have different values for different environments, keying on `Env` (see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/mappings-section-structure.html)
- For resources that shouldn't be deployed (e.g.) in prod environments I create a cloudformation condition.

So something like the following (there may be some errors here, I'm free handing this:

```yaml
Parameters:
  Env:
    Type: String
    AllowedValues: ['dev', 'prod']

Mappings:
  EnvironmentMap:
    dev:
      SqlSecurityGroupId: 'dev-sg'
      LambdaSubnet: 'lambda-dev-sg'
    prod:
      SqlSecurityGroupId: 'prod-sg'
      LambdaSubnet: 'lambda-prod-sg'

Conditions:
  IsProd: !Equals [!Ref Env, 'prod']

Resources:
  MyResource:
    Type: ..
    Properties:
      MySg: !FindInMap [EnvironmentMap, !Ref Env, SqlSecurityGroupId]

  ResourceOnlyForProd:
    Condition: IsProd
    Type: ..
    Properties: ..
```
